edemy_main_frontpage:
    path:           /{_locale}
    defaults:       { _controller: edemy.main:indexAction, _locale: es, _format: html }
    requirements:   { _locale: es|en, _format: html|xml }

edemy_css_file:
    path:           /mycss/{file}.css
    defaults:       { _controller: edemy.css:indexAction, _format: css }
    methods:        [ GET ]
    requirements:   { _format: css }

edemy_js_file:
    path:           /myjs/{file}.js
    defaults:       { _controller: edemy.js:indexAction, file: "main", _format: js }
    methods:        [ GET ]

login:
    path:   /login
    defaults:  { _controller: edemy.main:indexAction }

login_check:
    path:   /login_check

logout:
    path:   /logout

register:
    path:   /register
    defaults:  { _controller: edemy.main:indexAction }

edemy_logo_logo_show:
    path:           /admin/{_locale}/logo/show
    defaults:       { _controller: edemy.main:indexAction }
    methods:        [ GET ]
    requirements:   { _locale: es|en }

edemy_logo_logo_edit:
    path:           /admin/{_locale}/logo/edit
    defaults:       { _controller: edemy.main:indexAction }
    methods:        [ GET, POST ]
    requirements:   { _locale: es|en }