edemy_main_frontpage:
    path:           /{_locale}
    defaults:       { _controller: edemy.main:indexAction, _locale: es, _format: html }
    requirements:   { _locale: es|en, _format: html|xml }

edemy_css_file:
    path:           /mycss/{file}.{_format}
    defaults:       { _controller: edemy.css:indexAction, _format: css }
    methods:        [ GET ]
    requirements:   { _format: css }