services:
    edemy.routing_loader:
        class:  eDemy\MainBundle\Routing\RoutingLoader
        calls:
            - [setKernel, ["@kernel"]]
            - [setContainer, ["@service_container"]]
        tags:
            - { name: routing.loader }

    edemy.main:
        class: eDemy\MainBundle\Controller\MainController
        calls:
            - [setEventDispatcher, ["@event_dispatcher"]]
        tags:
            - { name: kernel.event_subscriber }

    edemy.param:
        class:  eDemy\MainBundle\Controller\ParamController
        calls:
            - [setEventDispatcher, ["@event_dispatcher"]]
        tags:
            - { name: kernel.event_subscriber }

    edemy.content:
         class: eDemy\MainBundle\Controller\ContentController
         calls:
             - [setEventDispatcher, ["@event_dispatcher"]]
         tags:
             - { name: kernel.event_subscriber }

    edemy.css:
        class:  eDemy\MainBundle\Controller\CssController
        calls:
            - [setEventDispatcher, ["@event_dispatcher"]]
        tags:
            - { name: kernel.event_subscriber }

    edemy.footer:
        class:  eDemy\MainBundle\Controller\FooterController
        calls:
            - [setEventDispatcher, ["@event_dispatcher"]]
        tags:
            - { name: kernel.event_subscriber }

    edemy.js:
        class:  eDemy\MainBundle\Controller\JsController
        calls:
            - [setEventDispatcher, ["@event_dispatcher"]]
        tags:
            - { name: kernel.event_subscriber }

    edemy.header:
        class:  eDemy\MainBundle\Controller\HeaderController
        calls:
            - [setEventDispatcher, ["@event_dispatcher"]]
        tags:
            - { name: kernel.event_subscriber }

    edemy.meta:
        class:  eDemy\MainBundle\Controller\MetaController
        calls:
            - [setEventDispatcher, ["@event_dispatcher"]]
        tags:
            - { name: kernel.event_subscriber }

    edemy.menu:
        class: eDemy\MainBundle\Controller\MenuController
        calls:
            - [setEventDispatcher, ["@event_dispatcher"]]
        tags:
            - { name: kernel.event_subscriber }

    edemy.redirect:
        class: eDemy\MainBundle\Controller\RedirectController
        calls:
            - [setEventDispatcher, ["@event_dispatcher"]]
        tags:
            - { name: kernel.event_subscriber }
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    edemy.servicecontainer:
        class: eDemy\MainBundle\Controller\ServiceContainerController
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_subscriber }

    edemy.twig.translation_extension:
        class:  eDemy\MainBundle\Twig\TranslationExtension
        calls:
             - [setEventDispatcher, ["@event_dispatcher"]]
        tags:
            - { name: twig.extension }

    edemy.twig.path_extension:
        class:  eDemy\MainBundle\Twig\PathExtension
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: twig.extension }

    edemy.twig.service_extension:
        class:  eDemy\MainBundle\Twig\ServiceExtension
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: twig.extension }

    edemy.user:
        class: eDemy\MainBundle\Controller\UserController
        calls:
            - [setEventDispatcher, ["@event_dispatcher"]]
        tags:
            - { name: kernel.event_subscriber }

    edemy.login:
        class:  eDemy\MainBundle\Controller\LoginController
        calls:
            - [setEventDispatcher, ["@event_dispatcher"]]
        tags:
            - { name: kernel.event_subscriber }