parameters:
    edemy.main.bundle:  "eDemy\MainBundle"

services:
    edemy.main:
        class: eDemy\MainBundle\Controller\MainController
        arguments: ["@event_dispatcher"]
        tags:
            - { name: kernel.event_subscriber }

    edemy.param:
        class:  eDemy\MainBundle\Controller\ParamController
        arguments: ["@event_dispatcher"]
        tags:
            - { name: kernel.event_subscriber }

    edemy.routing_loader:
        class:  eDemy\MainBundle\Routing\RoutingLoader
        arguments: ["@kernel", "@service_container"]
        tags:
            - { name: routing.loader }

    edemy.servicecontainer:
        class: eDemy\MainBundle\Controller\ServiceContainerController
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_subscriber }

    edemy.twig.translation_extension:
        class:  eDemy\MainBundle\Twig\TranslationExtension
        arguments: ["@event_dispatcher"]
        tags:
            - { name: twig.extension }

    edemy.twig.path_extension:
        class:  eDemy\MainBundle\Twig\PathExtension
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension }

    edemy.twig.service_extension:
        class:  eDemy\MainBundle\Twig\ServiceExtension
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension }
