services:
    edemy.routing_loader:
        class:  eDemy\MainBundle\Routing\RoutingLoader
        calls:
            - [setKernel, ["@kernel"]]
            - [setContainer, ["@service_container"]]
        tags:
            - { name: routing.loader }

    edemy.main:
        class: eDemy\MainBundle\Controller\MainController
        calls:
            - [setEventDispatcher, ["@event_dispatcher"]]
        tags:
            - { name: kernel.event_subscriber }

    edemy.param:
        class:  eDemy\MainBundle\Controller\ParamController
        calls:
            - [setEventDispatcher, ["@event_dispatcher"]]
        tags:
            - { name: kernel.event_subscriber }

    edemy.content:
         class: eDemy\MainBundle\Controller\ContentController
         calls:
             - [setEventDispatcher, ["@event_dispatcher"]]
         tags:
             - { name: kernel.event_subscriber }

    edemy.css:
        class:  eDemy\MainBundle\Controller\CssController
        calls:
            - [setEventDispatcher, ["@event_dispatcher"]]
        tags:
            - { name: kernel.event_subscriber }

    edemy.footer:
        class:  eDemy\MainBundle\Controller\FooterController
        calls:
            - [setEventDispatcher, ["@event_dispatcher"]]
        tags:
            - { name: kernel.event_subscriber }

    edemy.js:
        class:  eDemy\MainBundle\Controller\JsController
        calls:
            - [setEventDispatcher, ["@event_dispatcher"]]
        tags:
            - { name: kernel.event_subscriber }

    edemy.header:
        class:  eDemy\MainBundle\Controller\HeaderController
        calls:
            - [setEventDispatcher, ["@event_dispatcher"]]
        tags:
            - { name: kernel.event_subscriber }

    edemy.meta:
        class:  eDemy\MainBundle\Controller\MetaController
        calls:
            - [setEventDispatcher, ["@event_dispatcher"]]
        tags:
            - { name: kernel.event_subscriber }

    edemy.menu:
        class: eDemy\MainBundle\Controller\MenuController
        calls:
            - [setEventDispatcher, ["@event_dispatcher"]]
        tags:
            - { name: kernel.event_subscriber }

    edemy.redirect:
        class: eDemy\MainBundle\Controller\RedirectController
        calls:
            - [setEventDispatcher, ["@event_dispatcher"]]
        tags:
            - { name: kernel.event_subscriber }
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    edemy.servicecontainer:
        class: eDemy\MainBundle\Controller\ServiceContainerController
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_subscriber }

    edemy.twig.translation_extension:
        class:  eDemy\MainBundle\Twig\TranslationExtension
        calls:
             - [setEventDispatcher, ["@event_dispatcher"]]
        tags:
            - { name: twig.extension }

    edemy.twig.isloaded_extension:
        class: eDemy\MainBundle\Twig\IsLoadedExtension
        tags: [{ name: twig.extension }]

    edemy.twig.path_extension:
        class:  eDemy\MainBundle\Twig\PathExtension
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: twig.extension }

    edemy.twig.google_extension:
        class:  eDemy\MainBundle\Twig\GoogleExtension
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: twig.extension }

    edemy.twig.meta_extension:
        class:  eDemy\MainBundle\Twig\MetaExtension
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: twig.extension }

    edemy.twig.service_extension:
        class:  eDemy\MainBundle\Twig\ServiceExtension
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: twig.extension }

    edemy.user:
        class: eDemy\MainBundle\Controller\UserController
        calls:
            - [setEventDispatcher, ["@event_dispatcher"]]
        tags:
            - { name: kernel.event_subscriber }

    edemy.login:
        class:  eDemy\MainBundle\Controller\LoginController
        calls:
            - [setEventDispatcher, ["@event_dispatcher"]]
        tags:
            - { name: kernel.event_subscriber }

    edemy.logo:
        class:  eDemy\MainBundle\Controller\LogoController
        calls:
            - [setEventDispatcher, ["@event_dispatcher"]]
        tags:
            - { name: kernel.event_subscriber }

    edemy.twig.logo_extension:
        class: eDemy\MainBundle\Twig\LogoExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }

    edemy.contact:
        class: eDemy\MainBundle\Controller\ContactController
        calls:
            - [setEventDispatcher, ["@event_dispatcher"]]
        tags:
            - { name: kernel.event_subscriber }

    project_user.handler.logout_handler:
        class:  eDemy\MainBundle\Handler\LogoutHandler
        calls:
              - [setRouter, ["@router"]]
              - [setSession, ["@session"]]

    edemy.document:
        class: eDemy\MainBundle\Controller\DocumentController
        calls:
            - [setEventDispatcher, ["@event_dispatcher"]]
        tags:
            - { name: kernel.event_subscriber }

    edemy.analytics:
        class: eDemy\MainBundle\Controller\AnalyticsController
        calls:
            - [setEventDispatcher, ["@event_dispatcher"]]
        tags:
            - { name: kernel.event_subscriber }

    edemy.gallery:
        class: eDemy\MainBundle\Controller\GalleryController
        calls:
            - [setEventDispatcher, ["@event_dispatcher"]]
        tags:
            - { name: kernel.event_subscriber }

    edemy.google:
        class: eDemy\MainBundle\Controller\GoogleController
        calls:
            - [setEventDispatcher, ["@event_dispatcher"]]
        tags:
            - { name: kernel.event_subscriber }

    edemy.search:
        class: eDemy\MainBundle\Controller\SearchController
        calls:
            - [setEventDispatcher, ["@event_dispatcher"]]
        tags:
            - { name: kernel.event_subscriber }

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    edemy.sitemap:
        class: eDemy\MainBundle\Controller\SitemapController
        calls:
            - [setEventDispatcher, ["@event_dispatcher"]]
        tags:
            - { name: kernel.event_subscriber }

    anh_taggable.manager:
        class: Anh\Taggable\TaggableManager
        arguments:
            - @doctrine.orm.entity_manager
            - Anh\Taggable\Entity\Tag
            - Anh\Taggable\Entity\Tagging

    anh_taggable.subscriber:
        class: Anh\TaggableBundle\TaggableSubscriber
        arguments:
            - @service_container
        tags:
            - { name: doctrine.event_subscriber }

    truncatehtml.twig.extension:
        class: eDemy\MainBundle\Twig\TruncateHtmlExtension
        tags:
            - { name: twig.extension }

    edemy.twig.document_extension:
        class:  eDemy\MainBundle\Twig\DocumentExtension
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: twig.extension }
