parameters:
    edemy.main.bundle:  "eDemy\\MainBundle"

services:
    edemy.main:
        class: eDemy\MainBundle\Controller\MainController
        arguments: ["@event_dispatcher"]
        tags:
            - { name: kernel.event_subscriber }

    edemy.param:
        class:  %edemy.main.bundle%\Controller\ParamController
        arguments: ["@event_dispatcher"]
        tags:
            - { name: kernel.event_subscriber }

    edemy.routing_loader:
        class:  %edemy.main.bundle%\Routing\RoutingLoader
        arguments: ["@service_container", "@kernel"]
        tags:
            - { name: routing.loader }

    edemy.servicecontainer:
        class: %edemy.main.bundle%\Controller\ServiceContainerController
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: kernel.event_subscriber }

    edemy.twig.translation_extension:
        class:  %edemy.main.bundle%\Twig\TranslationExtension
        arguments: ["@event_dispatcher"]
        tags:
            - { name: twig.extension }

    edemy.twig.path_extension:
        class:  eDemy\MainBundle\Twig\PathExtension
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension }

    edemy.twig.service_extension:
        class:  %edemy.main.bundle%\Twig\ServiceExtension
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: twig.extension }
