<?php

namespace eDemy\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends EntityRepository
{
    public function findAllOrderedByTitle($namespace, $query = false)
    {
        $qb = $this->createQueryBuilder('d');
        $qb->andWhere('d.namespace = :namespace');
        $qb->orderBy('d.created','DESC');
        $qb->setParameter('namespace', $namespace);
        $query = $qb->getQuery();
        if($query) {
            return $query;
        } else {
            return $query->getResult();
        }
    }

    public function findLastModified($namespace = null)
    {
        $qb = $this->createQueryBuilder('d');
        if($namespace == null) {
            $qb->andWhere('d.namespace is null');
        } else {
            $qb->andWhere('d.namespace = :namespace');
            $qb->setParameter('namespace', $namespace);
        }
        $qb->orderBy('d.updated','DESC');
        $qb->setMaxResults(1);
        $query = $qb->getQuery();

        return $query->getSingleResult();
    }
}
