<?php

namespace eDemy\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ParamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParamRepository extends EntityRepository
{
    public function findLastAdminMenuModified($id, $namespace = null)
    {
        $qb = $this->createQueryBuilder('p');
        if($namespace == null) {
            $qb->andWhere('p.namespace is null');
        } else {
            $qb->andWhere('p.namespace = :namespace');
            $qb->setParameter('namespace', $namespace);
        }
        $qb->andWhere("p.type = 'adminmenu'");
        $qb->orderBy('p.updated','DESC');
        $qb->setMaxResults(1);
        $query = $qb->getQuery();

        return $query->getSingleResult();
    }

    public function findLastModified($namespace = null)
    {
        $qb = $this->createQueryBuilder('p');
        if($namespace == null) {
            $qb->andWhere('p.namespace is null');
        } else {
            $qb->andWhere('p.namespace = :namespace');
            $qb->setParameter('namespace', $namespace);
        }
//        $qb->andWhere('p.category = :category_id');
        $qb->orderBy('p.updated','DESC');
//        $qb->setParameter('category_id', $id);
        $qb->setMaxResults(1);
        $query = $qb->getQuery();

        return $query->getOneOrNullResult();
    }
}
